meerk40t/svgelements

setup.cfg, svg/elements/svg_elements.py
Corrects the image transforms for SVGImage.
=> Image Transform

setup.cfg, svg/elements/svg_elements.py, test/test_viewbox.py
Correct a crash if the viewport isn't correctly given.
=> Viewport None

setup.cfg, svg/elements/svg_elements.py, test/test_element.py, test/test_viewbox.py
All subclasses of SVGElement maintains a .values dictionary which contains the svg values given to that class. This permits all such produced values to allow additional parsing by agents.
=> SVGElements maintains values.

setup.cfg, svg/elements/svg_elements.py, test/test_matrix.py, test/test_paths.py
Fixes the inverse operation for the matrix.
Adds return of self to inverse() operation.
Adds dunder of '~' for matrix for invert() operation.
EG. "~Matrix("scale(0.5)") == scale(2)" is True.
=> Correction to inverse matrix and coverage.

svgelements/svgelements.py
Few small changes from the MeerK40t usages
=> 1.0.1 Updates

setup.cfg, svgelements/svgelements.py, test/test_angle.py, test/test_color.py, test/test_element.py, test/test_length.py, test/test_matrix.py, test/test_path.py, test/test_path_dunder.py, test/test_paths.py
=> Corrections for near collinear quads

setup.cfg, svgelements/svgelements.py, test/test_path.py
Corrects the SVGText bounds for rotated elements and corrects issue #45.
=> SvgText Bounds and Issue #45

setup.cfg, svgelements/svgelements.py
Corrects some issues with incomplete viewboxes.
=> 1.2.8 Update Improvement of Viewbox

svgelements/svgelements.py
* Adds shape.point() universal.
* Fixes a bug where reification would not clear out the cached `._length` and `._lengths` values.
=> Shape.point() universal.

setup.cfg, svgelements/svgelements.py, test/test_arc_length.py, test/test_cubic_bezier.py, test/test_quadratic_bezier.py, test/test_shape.py
In the header requires all users to import rather than just those calling npoint features.
Corrects #72 
See: meerk40t/meerk40t#270
@abey79 I've not actually checked the on the fly import checking for speed so if this gives you a performance hit you might want to make arrangements you feel are appropriate.
=> Softening numpy requirement

setup.cfg, svgelements/svgelements.py
* Math imports do not import * anymore, they only import those functions used in the code.
* Refined use of pi to use tau.
=> Math-Imports Refined

setup.cfg, svgelements/svgelements.py, test/test_path_segments.py
=> 1.4.9 Correct Degenerate Arc Bounding Box.

README.md, svgelements/svgelements.py, test/test_color.py
RGBA is the CSS standard, so the format is updated to align with this.
Also adding some tests that ensures the format accodring to RGBA and
updating the README.md with the changes made.
=> Changing ARGB format to RGBA

svgelements/svgelements.py
Opportunity for future code simplification to have a common routine for similar __str__ and __repr__ methods with the different attribute names passed as parameters.
=> Further __rep__ improvements

.github/workflows/codeql-analysis.yml, .github/workflows/python-code-quality.yml, .github/workflows/unittests.yml, pyproject.toml
Unittests fail with numpy and no scipy because e.g. the tests call `_length_exact` which does is not normally called and does not handle no scipy.
What I don't understand is how these tests succeed without scipy or numpy installed.
=> Implement code quality checks for svgelements

setup.cfg, svgelements/svgelements.py, test/test_text.py, test/test_viewbox.py
Text objects are SVGElements but are not processed by values for the SVGElement properties. Fixes #157
=> Issue #157 Correction

svgelements/svgelements.py, test/test_color.py
* adds basic support for BGR colors
=> Add Support for BGR colors.

.github/CODEOWNERS, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
...
1. Default PR reviewers
2. Code of Conduct
3. Simple PR Guidelines (for new contributors)
4. Simple Issue template
5. New style bug issue template. (Currently as an alternative to 4. with a view of removing 4. once it is shown to be working.)
Inspired by coming across https://github.com/Josee9988/project-template/tree/master/.github
Whilst these can be viewed in [Files changed](/meerk40t/svgelements/pull/162/files), they cannot be tested until they are merged.
=> Github repo configuration

svgelements/svgelements.py
See issue https://github.com/meerk40t/meerk40t/issues/1052
=> Fix style-import issue

setup.cfg, svgelements/svgelements.py, test/test_css.py, test/test_path_segments.py
=> Control Point Arc

svgelements/svgelements.py, test/test_use.py
=> Add Use.bbox()

svgelements/svgelements.py, test/test_write.py
Adds to the primary code base a `write` and `tostring` functions. These will be lossy but fairly robust and better than most people could write in a short period of time.
=> Issue 206 - Write Output

svgelements/svgelements.py, test/test_parsing.py
PR to correct issue 175 which was diagnosed for the reason of svg missing base svg element.
=> Correct Issue #175 - Non SVG Root Element

svgelements/svgelements.py, test/test_cubic_bezier.py
Fixes #214
There's an edge case when denom equals 0 which required a fallback.
=> Fixes Issue #214

svgelements/svgelements.py, test/test_cubic_bezier.py
=> Broaden the catch for numerical instability (Issue #220)

svgelements/svgelements.py, test/test_viewbox.py
* Correct an issue with Length == Length
* Correct an issue with Point(Length, Length) == Point(Length, Length)
* Add tests for other shapes to write to disk (Issue #228).
=> Check for remaining issues related to #228

svgelements/svgelements.py, test/test_matrix.py
* Update Perspective Mapping using newer equations for the unit square.
* Add Affine Mapping for the unit square (without point (1,1))
* Add tests for affine mapping.
=> Correct Perspective Matrix Mapping, Add Affine Mapping

svgelements/svgelements.py, test/test_image.py, test/test_parsing.py
=> Issue 239: Embedded Image Newlines 

svgelements/svgelements.py
font_weight was not passed in _write_node function
=> Pass Text font_weight value
